name: Restore cached node dependencies

runs:
  using: "composite"
  steps:
    - name: Restore root node_modules
      uses: actions/cache/restore@v4
      with:
        path: ./node_modules
        key: "${{ runner.os }}-node_modules-${{ env.NODE_VERSION }}-${{ hashFiles('**/package-lock.json') }}"
    - name: Restore angular node_modules
      uses: actions/cache/restore@v4
      with:
        path: ./packages/angular/node_modules
        key: "${{ runner.os }}-node_modules_angular-${{ env.NODE_VERSION }}-${{ hashFiles('./packages/angular/package-lock.json') }}"
