/* eslint-disable */
'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import React from 'react';
import { SgcButton as SgcButtonElement, defineCustomElement as defineSgcButton } from "swissgeol-core/components/sgc-button.js";
import { SgcIcon as SgcIconElement, defineCustomElement as defineSgcIcon } from "swissgeol-core/components/sgc-icon.js";

export type SgcButtonEvents = NonNullable<unknown>;

export const SgcButton: StencilReactComponent<SgcButtonElement, SgcButtonEvents> = /*@__PURE__*/ createComponent<SgcButtonElement, SgcButtonEvents>({
    tagName: 'sgc-button',
    elementClass: SgcButtonElement,
    // @ts-ignore - React type of Stencil Output Target may differ from the React version used in the Nuxt.js project, this can be ignored.
    react: React,
    events: {} as SgcButtonEvents,
    defineCustomElement: defineSgcButton
});

export type SgcIconEvents = NonNullable<unknown>;

export const SgcIcon: StencilReactComponent<SgcIconElement, SgcIconEvents> = /*@__PURE__*/ createComponent<SgcIconElement, SgcIconEvents>({
    tagName: 'sgc-icon',
    elementClass: SgcIconElement,
    // @ts-ignore - React type of Stencil Output Target may differ from the React version used in the Nuxt.js project, this can be ignored.
    react: React,
    events: {} as SgcIconEvents,
    defineCustomElement: defineSgcIcon
});
